runtime: python27
api_version: 1
threadsafe: false
handlers:
- url: /.*
  script: news-bias.my_app
libraries:
- name: numpy
  version: "1.6.1"
skip_files:
- X_train.pkl
- X_test.pkl
- y_train.pkl
- y_test.pkl
- all-the-news//articles.csv
- all-the-news//*
